swagger: "2.0"
info:
  title: LMS
  version: v1
host: localhost:3000
paths:
  /city:
    get:
      operationId: listVersionsv2
      summary: List API versions
      produces:
      - application/json
      responses:
        "200":
          description: |-
            response
consumes:
- application/json